image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - layout/node_modules/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

generate-stag-assets:
  stage: build
  script:
    - cd layout
    - npm install
    - npm run staging
  artifacts:
    paths:
      - layout/dist/
  only:
    - staging

generate-prod-assets:
  stage: build
  script:
    - cd layout
    - npm install
    - npm run prod
  artifacts:
    paths:
      - layout/dist/
  only:
    - master

deploy-assets-to-S3:
  stage: deploy
  script:
    - echo "Pushing the static files"
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - pip install awscli
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - aws s3 sync $CI_PROJECT_DIR/layout/dist s3://qudsinfowp/wp-content/themes/qudsinfo-wp-theme/layout/dist --acl public-read --delete
    - aws s3 sync $CI_PROJECT_DIR/layout/js s3://qudsinfowp/wp-content/themes/qudsinfo-wp-theme/layout/js --acl public-read --delete
  only:
    - master

deploy-theme-to-production:
  stage: deploy
  script:
    - echo "Copying files to DigitalOcean PRODUCTION droplet"
    - apt-get update -qy
    - apt-get install -y rsync
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh -p22 $SERVER_USER@$PRODUCTION_HOST "rm -rf www/qudsinfo/wp-content/themes/_tmp && mkdir www/qudsinfo/wp-content/themes/_tmp"
    - rsync -avh --exclude='*/node_modules/' ./ $SERVER_USER@$PRODUCTION_HOST:www/qudsinfo/wp-content/themes/_tmp
    - ssh -p22 $SERVER_USER@$PRODUCTION_HOST "mv www/qudsinfo/wp-content/themes/qudsinfo-wp-theme www/qudsinfo/wp-content/themes/_old && mv www/qudsinfo/wp-content/themes/_tmp www/qudsinfo/wp-content/themes/qudsinfo-wp-theme"
    - ssh -p22 $SERVER_USER@$PRODUCTION_HOST "rm -rf www/qudsinfo/wp-content/themes/_old"
  only:
    - master

deploy-theme-to-staging:
  stage: deploy
  script:
    - echo "Copying files to DigitalOcean STAGING droplet"
    - apt-get update -qy
    - apt-get install -y rsync
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - ssh -p22 $SERVER_USER@$STAGING_HOST "rm -rf www/qudsinfo/wp-content/themes/_tmp && mkdir www/qudsinfo/wp-content/themes/_tmp"
    - rsync -avh --exclude='*/node_modules/' ./ $SERVER_USER@$STAGING_HOST:www/qudsinfo/wp-content/themes/_tmp
    - ssh -p22 $SERVER_USER@$STAGING_HOST "mv www/qudsinfo/wp-content/themes/qudsinfo-wp-theme www/qudsinfo/wp-content/themes/_old && mv www/qudsinfo/wp-content/themes/_tmp www/qudsinfo/wp-content/themes/qudsinfo-wp-theme"
    - ssh -p22 $SERVER_USER@$STAGING_HOST "rm -rf www/qudsinfo/wp-content/themes/_old"
  only:
    - staging
