image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - layout/node_modules/

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

generate-assets:
  stage: build
  script:
    - cd layout
    - npm install
    - npm run css:build
  artifacts:
    paths:
      - layout/dist/

deploy-assets-to-S3:
  stage: deploy
  script:
    - echo "Pushing the static files"
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - mkdir ~/.aws/
    - touch ~/.aws/credentials
    - pip install awscli
    - printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
    - aws s3 sync $CI_PROJECT_DIR/layout/dist s3://qudsinfowp/wp-content/themes/qudsinfo-wp-theme/layout/dist --acl public-read --delete
  only:
    - master

deploy-theme-to-vps:
  stage: deploy
  script:
    - echo "Copying files to deigital ocean droplet"
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - ssh -p22 $SERVER_USER@$SERVER_IP "mkdir www/qudsinfo/wp-content/themes/_tmp"
    - scp -p22 -r * $SERVER_USER@$SERVER_IP:www/qudsinfo/wp-content/themes/_tmp
    - ssh -p22 $SERVER_USER@$SERVER_IP "mv www/qudsinfo/wp-content/themes/qudsinfo-wp-theme www/qudsinfo/wp-content/themes/_old && mv www/qudsinfo/wp-content/themes/_tmp www/qudsinfo/wp-content/themes/qudsinfo-wp-theme"
    - ssh -p22 $SERVER_USER@$SERVER_IP "rm -rf www/qudsinfo/wp-content/themes/_old"
  only:
    - master
