<?php

namespace QITheme\ACF;

class ContentFields extends BaseFields {

    public function fields()
    {
        acf_add_local_field_group(array(
            'key' => 'group_59e3a9a25266b',
            'title' => 'فريق المحتوى',
            'fields' => array(
                array(
                    'key' => 'field_59e3a9bd7da7c',
                    'label' => 'أقسام الصفحة',
                    'name' => 'sections',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        '59e3a9df97f2c' => array(
                            'key' => '59e3a9df97f2c',
                            'name' => 'infos',
                            'label' => 'المعلومات',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3aa207da7d',
                                    'label' => 'عدد المعلومات',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3ab3c4c05d',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3aa567da7e',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3ab5b4c05e' => array(
                            'key' => '59e3ab5b4c05e',
                            'name' => 'subjects',
                            'label' => 'المواضيع',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3ab5b4c05f',
                                    'label' => 'عدد المواضيع',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3ab5b4c060',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3ab5b4c061',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3aba64c062' => array(
                            'key' => '59e3aba64c062',
                            'name' => 'stories',
                            'label' => 'القصص',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3aba64c063',
                                    'label' => 'عدد القصص',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3aba64c064',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3aba64c065',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3abde4c066' => array(
                            'key' => '59e3abde4c066',
                            'name' => 'thoughts',
                            'label' => 'الخواطر',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3abde4c067',
                                    'label' => 'عدد الخواطر',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3abde4c068',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3abde4c069',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3abfc4c06a' => array(
                            'key' => '59e3abfc4c06a',
                            'name' => 'website_content',
                            'label' => 'محتوى الموقع',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3abfc4c06c',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3abfc4c06d',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'اضافة',
                    'min' => '',
                    'max' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/content.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

    }
}
