<?php
/**
 * Created by PhpStorm.
 * User: haitham
 * Date: 10/15/17
 * Time: 10:48 PM
 */
if (function_exists('acf_add_local_field_group')):
    function acf_add_local_field_groups()
    {

        acf_add_local_field_group(array(
            'key' => 'group_596f648e6d656',
            'title' => 'audio fields',
            'fields' => array(
                array(
                    'key' => 'field_57421cca56e8c',
                    'label' => 'رابط الساوند كلاود',
                    'name' => 'sc_link',
                    'type' => 'text',
                    'instructions' => 'رابط المقطع الصوتي على الساوند كلاود',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'none',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'audio',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(),
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_596f8b7d06056',
            'title' => 'Social Media Page',
            'fields' => array(
                array(
                    'key' => 'field_596f8b8b7b2bd',
                    'label' => 'مواقع التواصل',
                    'name' => 'social_links',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_596f8baf7b2be',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => '',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_596f8bd47b2bf',
                            'label' => 'رابط الموقع',
                            'name' => 'social_link',
                            'type' => 'url',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_596f8c197b2c0',
                            'label' => 'Classes',
                            'name' => 'classes',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_596f8c617b2c1',
                            'label' => 'الايقونة',
                            'name' => 'ico_class',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '30',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => 'fa-',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/social-media.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_596f648e9096b',
            'title' => 'Video Fields',
            'fields' => array(
                array(
                    'key' => 'field_5743702d5ee89',
                    'label' => 'رابط الفيديو',
                    'name' => 'yt_link',
                    'type' => 'text',
                    'instructions' => 'رابط الفيديو من اليوتيوب',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'videos',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(),
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59709753c7aeb',
            'title' => 'الأفرقة',
            'fields' => array(
                array(
                    'key' => 'field_5970975f8d54a',
                    'label' => 'فريق المحتوى',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_597098d802ae0',
                    'label' => 'صفحة نموذج الانتساب',
                    'name' => 'content_form_link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(),
                    'allow_null' => 0,
                    'allow_archives' => 0,
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_59709fad3eef3',
                    'label' => 'صورة فريق المحتوى',
                    'name' => 'content_image',
                    'type' => 'image',
                    'instructions' => 'وصف مختصر لفريق المحتوى',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5970988402adf',
                    'label' => 'وصف فريق المحتوى',
                    'name' => 'content_description',
                    'type' => 'wysiwyg',
                    'instructions' => 'وصف مختصر لفريق المحتوى',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'ضع وصف فريق المحتوى هنا',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_5970994002ae1',
                    'label' => 'فريق المحاضرات',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_5970995402ae2',
                    'label' => 'صفحة نموذج الانتساب',
                    'name' => 'lectures_form_link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(),
                    'allow_null' => 0,
                    'allow_archives' => 0,
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_5970a035fa012',
                    'label' => 'صورة فريق المحاضرات',
                    'name' => 'lectures_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5970995802ae3',
                    'label' => 'وصف فريق المحاضرات',
                    'name' => 'lectures_description',
                    'type' => 'wysiwyg',
                    'instructions' => 'وصف مختصر لفريق المحاضرات',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'ضع وصف فريق المحاضرات هنا',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
                array(
                    'key' => 'field_597099a402ae4',
                    'label' => 'الفريق الإعلامي',
                    'name' => '',
                    'type' => 'tab',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'placement' => 'top',
                    'endpoint' => 0,
                ),
                array(
                    'key' => 'field_597099ae02ae5',
                    'label' => 'صفحة نموذج الانتساب لفريق النشر',
                    'name' => 'media_form_link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(),
                    'allow_null' => 0,
                    'allow_archives' => 0,
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_5970a05e3376b',
                    'label' => 'صورة الفريق الإعلامي',
                    'name' => 'media_image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'id',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),

                array(
                    'key' => 'field_597099ae02aw6',
                    'label' => 'صفحة نموذج الانتساب لفريق الأخبار',
                    'name' => 'news_form_link',
                    'type' => 'page_link',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(),
                    'allow_null' => 0,
                    'allow_archives' => 0,
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_597099b102ae6',
                    'label' => 'وصف الفريق الإعلامي',
                    'name' => 'media_description',
                    'type' => 'wysiwyg',
                    'instructions' => 'وصف مختصر للفريق الإعلامي',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 'ضع وصف الفريق الإعلامي هنا',
                    'tabs' => 'all',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'delay' => 0,
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/joinus.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'the_content',
                1 => 'comments',
            ),
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59dbba6db00bd',
            'title' => 'الموضوعات',
            'fields' => array(
                array(
                    'key' => 'field_59dbbb2d90387',
                    'label' => 'التصنيف',
                    'name' => 'category',
                    'type' => 'taxonomy',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'taxonomy' => 'category',
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'add_term' => 1,
                    'save_terms' => 1,
                    'load_terms' => 1,
                    'return_format' => 'object',
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_59dbba7f90384',
                    'label' => 'الفقرات',
                    'name' => 'paragraphs',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => '',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'row',
                    'button_label' => 'إضافة فقرة',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_59dbbaae90385',
                            'label' => 'العنوان',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_59dbbadd90386',
                            'label' => 'نص الفقرة',
                            'name' => 'text',
                            'type' => 'wysiwyg',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'tabs' => 'visual',
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                            'delay' => 0,
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'info-details',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59e83ad219a2x',
            'title' => 'تفاصيل المعلم',
            'fields' => array(
                array(
                    'key' => 'field_59e83af44e2fc',
                    'label' => 'موقع المعلم',
                    'name' => 'location_to_dome',
                    'type' => 'text',
                    'instructions' => ' بالنسبة لقبة الصخرة',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_59e83b1d4e2fd',
                    'label' => 'تاريخ بناء المعلم',
                    'name' => 'building_history',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'br',
                ),
                array(
                    'key' => 'field_59e83b414e2fe',
                    'label' => 'سبب التسمية',
                    'name' => 'name_reason',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'br',
                ),
                array(
                    'key' => 'field_59e83b754e2ff',
                    'label' => 'اسم الباني',
                    'name' => 'builtby',
                    'type' => 'text',
                    'instructions' => 'من بنى المعلم؟',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'pics',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 0,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59becab129da6',
            'title' => 'صور الألبوم',
            'fields' => array(
                array(
                    'key' => 'field_59becabbfe863',
                    'label' => 'اختر الصور',
                    'name' => 'gallery_images',
                    'type' => 'gallery',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'insert' => 'append',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => 'png,jpg,jpeg',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'pics',
                    ),
                ),
            ),
            'menu_order' => 1,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59e2037fd69f0',
            'title' => 'صورة المنتج للتطبيق',
            'fields' => array(
                array(
                    'key' => 'field_59e203a51aa9f',
                    'label' => 'اختر الصورة',
                    'name' => 'image_app',
                    'type' => 'image',
                    'instructions' => 'هذه الصورة فقط للظهور في تطبيق معلومة مقدسية',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'preview_size' => 'thumbnail',
                    'library' => 'uploadedTo',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'products',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'side',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => 'هذه الصورة فقط للظهور في تطبيق معلومة مقدسية',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59e3a9a25266b',
            'title' => 'فريق المحتوى',
            'fields' => array(
                array(
                    'key' => 'field_59e3a9bd7da7c',
                    'label' => 'أقسام الصفحة',
                    'name' => 'sections',
                    'type' => 'flexible_content',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layouts' => array(
                        '59e3a9df97f2c' => array(
                            'key' => '59e3a9df97f2c',
                            'name' => 'infos',
                            'label' => 'المعلومات',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3aa207da7d',
                                    'label' => 'عدد المعلومات',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3ab3c4c05d',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3aa567da7e',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3ab5b4c05e' => array(
                            'key' => '59e3ab5b4c05e',
                            'name' => 'subjects',
                            'label' => 'المواضيع',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3ab5b4c05f',
                                    'label' => 'عدد المواضيع',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3ab5b4c060',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3ab5b4c061',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3aba64c062' => array(
                            'key' => '59e3aba64c062',
                            'name' => 'stories',
                            'label' => 'القصص',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3aba64c063',
                                    'label' => 'عدد القصص',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3aba64c064',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3aba64c065',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3abde4c066' => array(
                            'key' => '59e3abde4c066',
                            'name' => 'thoughts',
                            'label' => 'الخواطر',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3abde4c067',
                                    'label' => 'عدد الخواطر',
                                    'name' => 'total_number',
                                    'type' => 'number',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                    'min' => 0,
                                    'max' => '',
                                    'step' => '',
                                ),
                                array(
                                    'key' => 'field_59e3abde4c068',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3abde4c069',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                        '59e3abfc4c06a' => array(
                            'key' => '59e3abfc4c06a',
                            'name' => 'website_content',
                            'label' => 'محتوى الموقع',
                            'display' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_59e3abfc4c06c',
                                    'label' => 'النص',
                                    'name' => 'text',
                                    'type' => 'textarea',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'placeholder' => '',
                                    'maxlength' => '',
                                    'rows' => '',
                                    'new_lines' => 'wpautop',
                                ),
                                array(
                                    'key' => 'field_59e3abfc4c06d',
                                    'label' => 'الصورة',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'uploadedTo',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                            'min' => '',
                            'max' => '',
                        ),
                    ),
                    'button_label' => 'اضافة',
                    'min' => '',
                    'max' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/content.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_5a77fcad3b0d9',
            'title' => 'المحاضرات',
            'fields' => array(
                array(
                    'key' => 'field_5a77fcba419ae',
                    'label' => 'عنوان فرعي',
                    'name' => 'subtitle',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/lectures.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'seamless',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_596f648e80ec2',
            'title' => 'فريق المحاضرات',
            'fields' => array(
                array(
                    'key' => 'field_57544577d06af',
                    'label' => 'عدد المحاضرات',
                    'name' => 'numlects',
                    'type' => 'number',
                    'instructions' => 'عدد المحاضرات التي تم إعطاءها',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 5,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => 1,
                ),
                array(
                    'key' => 'field_575445e0d06b0',
                    'label' => 'عدد الساعات',
                    'name' => 'numhours',
                    'type' => 'number',
                    'instructions' => 'مجموع الساعات التي تم إعطاءها من قبل الفريق',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 3,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => 1,
                ),
                array(
                    'key' => 'field_57544649d06b1',
                    'label' => 'مجموع اعداد الحضور',
                    'name' => 'aud_sum',
                    'type' => 'number',
                    'instructions' => 'مجموع اعداد حضور جميع المحاضرات',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => 1,
                ),
                array(
                    'key' => 'field_59e2558eac455',
                    'label' => 'رقم التواصل مع الفريق',
                    'name' => 'phone_num',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_59e25aa5eac455',
                    'label' => 'البريد الإلكتروني',
                    'name' => 'email_add',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_5a22x9870c519',
                    'label' => 'أهداف الفريق',
                    'name' => 'goals',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_5a63ax65d3591',
                    'min' => 1,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'إضافة هدف',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5a63ax65d3591',
                            'label' => 'نص الهدف',
                            'name' => 'goal_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_5a63a9870c519',
                    'label' => 'ماذا نقدم؟',
                    'name' => 'offers',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_5a63aa65d3591',
                    'min' => 1,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'إضافة خدمة',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5a63aa65d3591',
                            'label' => 'اسم الخدمة',
                            'name' => 'service_name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5a63ab77446f5',
                            'label' => 'وصف صغير',
                            'name' => 'short_desc',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
                array(
                    'key' => 'field_596f5a0aaf9f9',
                    'label' => 'صور المحاضرات',
                    'name' => 'gallery',
                    'type' => 'gallery',
                    'instructions' => 'ارفع صور محاضرات معلومة مقدسية السابقة هنا',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'min' => '',
                    'max' => '',
                    'insert' => 'append',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5a7b545a71ee7',
                    'label' => 'مادة المحاضرات',
                    'name' => 'material',
                    'type' => 'file',
                    'instructions' => 'ارفع ملف مادة المحاضرات هنا',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_5a7b5745832dd',
                    'label' => 'رابط الانضمام',
                    'name' => 'join_link',
                    'type' => 'page_link',
                    'instructions' => 'اختر صفحة الانضمام لفريق المحاضرات',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'page',
                    ),
                    'taxonomy' => array(),
                    'allow_null' => 0,
                    'allow_archives' => 1,
                    'multiple' => 0,
                ),
            ),
            'location' => array(
	            array(
		            array(
			            'param' => 'page_template',
			            'operator' => '==',
			            'value' => 'page-templates/lectures.php',
		            ),
	            ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'field',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59e262c3b955c',
            'title' => 'معلومات الفريق',
            'fields' => array(
                array(
                    'key' => 'field_59e262c90c465',
                    'label' => 'رقم التواصل',
                    'name' => 'phone_num',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_59e262da0c466',
                    'label' => 'رقم الواتساب',
                    'name' => 'whatsapp_num',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_59e262f70c467',
                    'label' => 'البريد الالكتروني',
                    'name' => 'email',
                    'type' => 'email',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'page',
                    ),
                    array(
                        'param' => 'page_template',
                        'operator' => '==',
                        'value' => 'page-templates/aboutus.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_596f648e74a9a',
            'title' => 'معلومات الكتاب',
            'fields' => array(
                array(
                    'key' => 'field_580b97ed0f8fb',
                    'label' => 'مؤلف الكتاب',
                    'name' => 'book_author_f',
                    'type' => 'taxonomy',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'taxonomy' => 'book_authors',
                    'field_type' => 'select',
                    'allow_null' => 0,
                    'add_term' => 1,
                    'save_terms' => 1,
                    'load_terms' => 1,
                    'return_format' => 'object',
                    'multiple' => 0,
                ),
                array(
                    'key' => 'field_580b9a0550fc9',
                    'label' => 'ارفع الكتاب هنا',
                    'name' => 'download_link',
                    'type' => 'file',
                    'instructions' => 'ارفع الكتاب إن كان موجود',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'return_format' => 'url',
                    'library' => 'uploadedTo',
                    'min_size' => '',
                    'max_size' => '',
                    'mime_types' => '',
                ),
                array(
                    'key' => 'field_580bbebcf617a',
                    'label' => 'رابط خارجي للكتاب',
                    'name' => 'external_link',
                    'type' => 'link_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                ),
                array(
                    'key' => 'field_59d7d103a8d15',
                    'label' => 'سنة النشر',
                    'name' => 'release_date',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 2017,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_59d7d18ca8d16',
                    'label' => 'عدد الصفحات',
                    'name' => 'num_pages',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => 0,
                    'max' => '',
                    'step' => '',
                ),
                array(
                    'key' => 'field_5b37d8a80dc7c',
                    'label' => 'اقتباس',
                    'name' => 'quote',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'اقتباس مختصر من الكتاب...',
                    'maxlength' => '',
                    'rows' => '',
                    'new_lines' => 'br',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'book',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'left',
            'instruction_placement' => 'label',
            'hide_on_screen' => array(
                0 => 'discussion',
                1 => 'categories',
                2 => 'tags',
                3 => 'send-trackbacks',
            ),
            'active' => 1,
            'description' => '',
        ));

        acf_add_local_field_group(array(
            'key' => 'group_59e507d37ee42',
            'title' => 'تفاصيل المنتج',
            'fields' => array(
                array(
                    'key' => 'field_59e507f1dc251',
                    'label' => 'لون الخلفية',
                    'name' => 'bg_color',
                    'type' => 'color_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'products',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));


        acf_add_local_field_group(array(
            'key' => 'group_5c17f3a268c70',
            'title' => 'فريق عمل الموقع',
            'fields' => array(
                array(
                    'key' => 'field_5c17f3d93c8fd',
                    'label' => 'أعضاء فريق الموقع',
                    'name' => 'members',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'collapsed' => 'field_5c17f4733c8fe',
                    'min' => 0,
                    'max' => 0,
                    'layout' => 'table',
                    'button_label' => 'إضافة عضو',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5c17f4733c8fe',
                            'label' => 'اسم العضو',
                            'name' => 'name',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5c17f48f3c8ff',
                            'label' => 'الوظيفة',
                            'name' => 'job',
                            'type' => 'select',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'مصور معالم' => 'مصور معالم',
                                'مبرمج ومصمم الموقع' => 'مبرمج ومصمم الموقع',
                                'محرر ومنسق محتوى' => 'محرر ومنسق محتوى',
                                'ناشر أخبار' => 'ناشر أخبار',
                            ),
                            'default_value' => array(),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'ui' => 0,
                            'return_format' => 'value',
                            'ajax' => 0,
                            'placeholder' => '',
                        ),
                        array(
                            'key' => 'field_5c17f533727e2',
                            'label' => 'صورة',
                            'name' => 'picture',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'uploadedTo',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_5c17f4733c8aa',
                            'label' => 'للتواصل',
                            'name' => 'contact',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_template',
                        'operator' => '==',
                        'value' => 'page-templates/team.php',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'acf_after_title',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => 1,
            'description' => '',
        ));


    }

    add_action('acf/init', 'acf_add_local_field_groups');


    acf_add_local_field_group(array(
        'key' => 'group_5c51f35614dcf',
        'title' => 'إنجازات فريق الأخبار',
        'fields' => array(
            array(
                'key' => 'field_5c51f35e7479e',
                'label' => 'عدد الأخبار',
                'name' => 'news_count',
                'type' => 'number',
                'instructions' => 'عدد الأخبار التي تم نشرها',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5c51f3c47479f',
                'label' => 'عدد التقارير',
                'name' => 'reports_count',
                'type' => 'number',
                'instructions' => 'عدد التقارير التي تم إعدادها',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-templates/news-team.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));


    acf_add_local_field_group(array(
        'key' => 'group_5c5336e5473bc',
        'title' => 'الخلفيات',
        'fields' => array(
            array(
                'key' => 'field_5c5336f9d2cff',
                'label' => 'صورة سطح المكتب',
                'name' => 'desktop',
                'type' => 'image',
                'instructions' => 'خلفية سطح المكتب',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'illdy-info',
                'library' => 'uploadedTo',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5c533780d2cdd',
                'label' => 'صورة الهاتف المحمول',
                'name' => 'mobile',
                'type' => 'image',
                'instructions' => 'خلفية الموبايل',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'illdy-info',
                'library' => 'uploadedTo',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'wallpapers',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));


    acf_add_local_field_group(array(
        'key' => 'group_5d38a7c6f2c14',
        'title' => 'مصدر المعلومة',
        'fields' => array(
            array(
                'key' => 'field_5d38a82c24659',
                'label' => 'مصدر المعلومة',
                'name' => 'source',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));


endif;